# Generated by Django 4.0.4 on 2022-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_entry_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_req',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='loading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='seal_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
