# Generated by Django 4.0.4 on 2022-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
