# Generated by Django 4.0.4 on 2022-07-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_created_date_sale_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cheque_dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
